### ISSUE TITLE
Setting postition of Motor

### ISSUE THREAD

**Issue by nicksauerwein** [NativeDesign/python-tmcl#3]
Hey,

I connected to the motor using the following command:
```python
import TMCL
from serial import Serial

serial_port = Serial("/dev/ttyUSB0")
bus = TMCL.connect(serial_port)
motor = bus.get_motor(1)
```

Now I tried to change the position of the motors with:
```python
motor.axis.target_position =  1000
```

This throws however an error:
```python
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-57-c95689c0c7e5> in <module>()
----> 1 motor.axis.target_speed = 1000

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in target_speed(self, value)
     73     @target_speed.setter
     74     def target_speed(self, value):
---> 75         return self.set( 2, value )
     76 
     77     @property

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in set(self, param, value)
     47 
     48     def set (self, param, value):
---> 49         reply = self.motor.send( Command.SAP, param, self.motor.motor, value)
     50         return reply.status
     51 

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/motor.py in send(self, cmd, type, motorbank, value)
     14 
     15     def send (self, cmd, type, motorbank, value):
---> 16         return self.bus.send(self.address, cmd, type, motorbank, value)
     17 
     18     def stop (self):

/home/maxk/anaconda3/lib/python3.6/site-packages/TMCL/bus.py in send(self, address, command, type, motorbank, value)
     35         else:
     36             checksum = address + command + type + motorbank + value
---> 37             msg = struct.pack(MSG_STRUCTURE, address, command, type, motorbank, value, checksum)
     38             self.serial.write(msg)
     39             rep = self.serial.read(REPLY_LENGTH)

error: ubyte format requires 0 <= number <= 255
```
BUT when I do `motor.axis.actual_position` I get 1194071. What am I doing wrong?

**Comment by alanpich** [comment]
it looks as if you are setting `motor.axis.target_speed` rather than `motor.axis.target_position`.

If you are trying to move the motor to a specified position, you would want to send the `MVP` (**M**o**V**e-to-**P**osition) command.

I've just pushed a load of updates to the library. It's not been submitted as a new version to pypi/pip yet, but I'd be obliged if you could test the changes out for me (i haven't got a motor to hand) by cloning the repo and installing manually.

I've added some utility methods that should make your life easier:
- `motor.rotate_left(speed)`
- `motor.rotate_right(speed)`
- `motor.move_relative(offset)`
- `motor.move_absolute(position)`

**Comment by nicksauerwein** [comment]
This is very nice. I will install the update tomorrow on my machine and test all the commands. I will let you know if I find any problems.
